package com.wfhwfo.attendance.common.enums;

public enum AutoTrackingStateLabel {
    WAITING_FOR_PERMISSION,
    LOCATION_PERMISSION_DENIED,
    DETECTING_LOCATION,
    INSIDE_OFFICE,
    OUTSIDE_OFFICE,
    AUTO_CHECKIN_PENDING,
    AUTO_CHECKED_IN,
    CHECKED_IN_WFO,
    CHECKED_IN_WFH,
    AUTO_CHECKOUT_MONITORING_ACTIVE,
    WFH_CONFIRMATION_REQUIRED,
    NOT_CHECKED_IN,
    AUTO_CHECKOUT_PENDING,
    AUTO_CHECKED_OUT,
    CHECKED_OUT,
    SYSTEM_CLOSED,
    MISSING_CHECKOUT
}
